### ISSUE TITLE
Compatibility issue with fish 2.5

### ISSUE THREAD

**Issue by iamthad** [purcell/exec-path-from-shell#57] opened 2017-02-04 13:39 UTC
As reported in a [spacemacs issue thread](https://github.com/syl20bnr/spacemacs/issues/4755#issuecomment-277375043), there is an issue with the latest version of fish, resulting in the message:

    Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: ""

**Comment by lvh** [comment] 2017-02-04 15:17
A different issue for this has already been opened and closed:

https://github.com/purcell/exec-path-from-shell/issues/56

It is almost certainly not an exec-path-from-shell bug.  See https://github.com/fish-shell/fish-shell/issues/3809#issuecomment-277400905 for details and https://github.com/syl20bnr/spacemacs/issues/4755#issuecomment-277452286 for a specific remedy if you're using `thefuck`.

**Comment by purcell** [comment] 2017-02-05 03:16
Yep, duplicate of #56.

**Closed by purcell** 2017-02-05 03:16 UTC

**Comment by iamthad** [comment] 2017-02-05 15:02
My apologies for the dupe.
